version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aves-colombia-db
      POSTGRES_USER: aves
      POSTGRES_PASSWORD: aves12345
    ports:
      - "5433:5432"

  web:
    build: .
    command: python ./src/app.py
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://aves:aves12345@db:5432/aves-colombia-db
