services:
  postgres:
    image: postgres:16.0
    container_name: aves_db
    restart: always
    env_file:
      - .development.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    networks:
      - aves-network

  admin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: aves@gmail.com
        PGADMIN_DEFAULT_PASSWORD: aves12345

networks:
  aves-network:
    driver: bridge