version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: aves_colombia_db
      POSTGRES_USER: aves
      POSTGRES_PASSWORD: aves12345
    ports:
      - "5433:5432"

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - db

volumes:
  postgres_data: